[package]
name = "appv3-jsplugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dunce.workspace = true
appv3-core.workspace = true
tokio.workspace = true
serde_json.workspace = true
tracing.workspace = true
reqwest.workspace = true
sha2.workspace = true
uuid.workspace = true
chrono.workspace = true
regex.workspace = true
fancy-regex = "0.14"
base64 = "0.23"
hex = "0.4"
rand = "0.8"
rquickjs = { version = "0.14", features = ["futures", "loader"] }
oxc_allocator = "0.146"
oxc_codegen = "0.146"
oxc_diagnostics = "0.146"
oxc_parser = "0.146"
oxc_semantic = "0.146"
oxc_span = "0.146"
oxc_transformer = "0.146"

[dev-dependencies]
tempfile = "3"
