"""Shared ignore helpers for filesystem tools and the workspace file listing.

Two policies live here, used by ``grep``, ``glob`` and the API's workspace
listing so a file is never visible to one and invisible to another:

1. :data:`NOISE_DIR_NAMES` — directory trees that are machine-generated and
   never hand-authored. Skipped outright, before any ``.gitignore`` lookup.
2. :func:`is_gitignored` — a ``gitignore(5)`` matcher for everything else.

The matcher used to be a thin ``fnmatch`` wrapper, which was wrong in both
directions: ``fnmatch``'s ``*`` crosses ``/``, so ``docs/*.tmp`` also hid
``docs/guide/deep/notes.tmp`` (a file git shows), while directory patterns were
anchored to the root, so ``build/`` never matched ``web/build/`` (a directory
git ignores). Wildcard scope is now git's: ``*`` and ``?`` stop at ``/`` and
only ``**`` spans directories.

Known limitation: only the ``.gitignore`` at the search root is read — nested
``.gitignore`` files, ``.git/info/exclude`` and ``core.excludesFile`` are not.
Callers that need exact fidelity should ask git itself; see
``_git_listed_paths`` in ``app/api/routes/team/files.py``.
"""

from __future__ import annotations

import re
from functools import lru_cache
from pathlib import Path

#: Directories whose contents are generated by a tool, not written by a human:
#: dependency trees and compiler/test caches. Skipped without consulting
#: ``.gitignore`` so a repo that forgot to ignore ``node_modules`` doesn't
#: swamp every search.
#:
#: Deliberately excludes ``dist/`` and ``build/``: those regularly hold real
#: content (a site the agent just built, a tracked ``build/Dockerfile``), and
#: pruning them unconditionally made those files unsearchable and impossible to
#: @-mention. Whether they are noise is left to ``.gitignore``.
NOISE_DIR_NAMES = frozenset(
    {
        ".git",
        "node_modules",
        ".venv",
        "venv",
        "__pycache__",
        ".mypy_cache",
        ".ruff_cache",
        ".pytest_cache",
        ".tox",
        ".nox",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".turbo",
        ".parcel-cache",
        ".gradle",
        ".terraform",
    }
)

_MAX_CACHED_PATTERNS = 1024


class GitignoreRules(list):
    """Ordered ``(pattern, is_negation)`` rules that can prefilter themselves.

    A plain list of pairs, so every existing caller and comparison keeps
    working — it just carries a lazily-built union matcher used to answer
    "no rule can possibly match this path" in two regex operations per path
    component instead of one per rule. A repository with 127 rules was
    spending 219,456 pattern checks on 1,728 paths.

    The union is built once, on first use, so the rules must not be mutated
    after loading. Nothing does: callers load them and pass them through.
    """

    _union: "tuple[re.Pattern[str] | None, re.Pattern[str] | None] | None" = None

    def union(self) -> "tuple[re.Pattern[str] | None, re.Pattern[str] | None]":
        """``(name_union, path_union)``, compiled once per rule set.

        Non-anchored patterns are only ever tested against a single path
        component, anchored ones only against a path prefix, so they union
        separately. ``directory_only`` is deliberately ignored here: including
        those rules can only make the union match *more* often, and a false
        positive costs one slow-path walk while a false negative would
        silently un-ignore a file.
        """
        if self._union is None:
            names: list[str] = []
            paths: list[str] = []
            for pattern, _include in self:
                spec = _compile_pattern(pattern)
                if spec is None:
                    continue
                (paths if spec.anchored else names).append(spec.source)
            self._union = (_compile_union(names), _compile_union(paths))
        return self._union


def _compile_union(bodies: list[str]) -> "re.Pattern[str] | None":
    """One alternation over *bodies*, or ``None`` when there is nothing to try."""
    if not bodies:
        return None
    joined = "|".join(f"(?:{body})" for body in bodies)
    try:
        return re.compile(f"(?s:{joined})\\Z")
    except re.error:
        return None  # fall back to rule-by-rule matching


def load_gitignore_rules(root: Path) -> GitignoreRules:
    """Parse ``root/.gitignore`` into ``(pattern, is_negation)`` pairs.

    Order is preserved: :func:`is_gitignored` applies last-match-wins, so a
    later ``!pattern`` can re-include what an earlier rule excluded.
    """
    gitignore = root / ".gitignore"
    if not gitignore.is_file():
        return GitignoreRules()
    try:
        lines = gitignore.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return GitignoreRules()

    rules: list[tuple[str, bool]] = []
    for line in lines:
        pattern = line.strip()
        if not pattern or pattern.startswith("#"):
            continue
        include = pattern.startswith("!")
        if include:
            pattern = pattern[1:].strip()
        elif pattern.startswith(("\\!", "\\#")):
            # Escaped leading marker: the file is literally named "!foo"/"#foo".
            pattern = pattern[1:]
        if pattern:
            rules.append((pattern, include))
    return GitignoreRules(rules)


class _PatternSpec:
    """A gitignore pattern compiled to a regex, plus its matching mode."""

    __slots__ = ("regex", "directory_only", "anchored", "source")

    def __init__(
        self,
        regex: re.Pattern[str],
        directory_only: bool,
        anchored: bool,
        source: str,
    ):
        self.regex = regex
        self.directory_only = directory_only
        self.anchored = anchored
        self.source = source


def _translate(glob: str) -> str:
    """Translate one gitignore path glob into a regex body.

    Differs from :func:`fnmatch.translate` in exactly the way that matters:
    ``*`` and ``?`` never match ``/``, and ``**`` is recognised as the
    directory-spanning wildcard.
    """
    out: list[str] = []
    i = 0
    n = len(glob)
    while i < n:
        ch = glob[i]
        if ch == "\\" and i + 1 < n:
            out.append(re.escape(glob[i + 1]))
            i += 2
            continue
        if ch == "*":
            if glob.startswith("**", i):
                i += 2
                # "foo/**" — everything below foo.
                if i == n:
                    out.append(".*")
                # "**/" — zero or more leading directories.
                elif glob[i] == "/":
                    out.append("(?:.*/)?")
                    i += 1
                else:
                    out.append(".*")
                continue
            out.append("[^/]*")
            i += 1
            continue
        if ch == "?":
            out.append("[^/]")
            i += 1
            continue
        if ch == "[":
            end = glob.find("]", i + 1)
            if end == -1:
                out.append(re.escape(ch))
                i += 1
                continue
            body = glob[i + 1 : end]
            if body.startswith(("!", "^")):
                body = "^" + body[1:]
            out.append(f"[{body}]")
            i = end + 1
            continue
        out.append(re.escape(ch))
        i += 1
    return "".join(out)


@lru_cache(maxsize=_MAX_CACHED_PATTERNS)
def _compile_pattern(pattern: str) -> _PatternSpec | None:
    directory_only = pattern.endswith("/")
    body = pattern[:-1] if directory_only else pattern
    # A slash anywhere but the end anchors the pattern to the .gitignore's
    # directory; without one, the pattern matches an entry name at any depth.
    anchored = "/" in body
    body = body.lstrip("/")
    if not body:
        return None
    try:
        regex = re.compile(f"(?s:{_translate(body)})\\Z")
    except re.error:
        return None
    return _PatternSpec(regex, directory_only, anchored, _translate(body))


def matches_gitignore_pattern(pattern: str, rel: str, *, is_dir: bool) -> bool:
    """True when ``rel`` is matched by a single ``.gitignore`` pattern.

    ``rel`` is POSIX-relative to the directory holding the ``.gitignore``.
    Ancestor directories are tested too, because ignoring a directory ignores
    everything beneath it — callers that pass a file path straight in (rather
    than pruning during a walk) still get the right answer.
    """
    spec = _compile_pattern(pattern)
    if spec is None:
        return False

    parts = [part for part in rel.split("/") if part]
    if not parts:
        return False

    last = len(parts) - 1
    for index, name in enumerate(parts):
        # Every component except the final one is, by construction, a directory.
        entry_is_dir = is_dir if index == last else True
        if spec.directory_only and not entry_is_dir:
            continue
        target = "/".join(parts[: index + 1]) if spec.anchored else name
        if spec.regex.match(target):
            return True
    return False


def is_gitignored(rel: str, *, is_dir: bool, rules: list[tuple[str, bool]]) -> bool:
    """Apply ``rules`` to ``rel``, last match wins (so ``!`` can re-include)."""
    # Most paths match no rule at all. Ask the union first and skip the
    # per-rule walk entirely when it says no rule can apply.
    if isinstance(rules, GitignoreRules) and not _union_may_match(rel, rules.union()):
        return False
    ignored = False
    for pattern, include in rules:
        if matches_gitignore_pattern(pattern, rel, is_dir=is_dir):
            ignored = not include
    return ignored


def _union_may_match(
    rel: str, union: "tuple[re.Pattern[str] | None, re.Pattern[str] | None]"
) -> bool:
    """True when some rule *could* match ``rel`` — a superset of the real answer."""
    name_union, path_union = union
    if name_union is None and path_union is None:
        return False
    parts = [part for part in rel.split("/") if part]
    if not parts:
        return False
    if name_union is not None:
        for name in parts:
            if name_union.match(name):
                return True
    if path_union is not None:
        prefix = ""
        for name in parts:
            prefix = f"{prefix}/{name}" if prefix else name
            if path_union.match(prefix):
                return True
    return False
